/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffee.shop;

import java.text.DecimalFormat;

/**
 *
 * @author mahmo
 */
public class coffee extends javax.swing.JFrame {

    /**
     * Creates new form coffee
     */
    public coffee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        radtea = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        radcoffe = new javax.swing.JRadioButton();
        radyansun = new javax.swing.JRadioButton();
        radcola = new javax.swing.JRadioButton();
        btnenter = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        chN3na3 = new javax.swing.JCheckBox();
        chMilk = new javax.swing.JCheckBox();
        chToast = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtsub = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txttax = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txttotal = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radtea.setText("Tea  1");
        radtea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radteaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Coffee Shop");
        jLabel1.setPreferredSize(new java.awt.Dimension(90, 20));

        radcoffe.setText("Coffee 1.5");
        radcoffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radcoffeActionPerformed(evt);
            }
        });

        radyansun.setText("yansun 1.25");
        radyansun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radyansunActionPerformed(evt);
            }
        });

        radcola.setText("Cola 2.5");
        radcola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radcolaActionPerformed(evt);
            }
        });

        btnenter.setText("Enter");
        btnenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenterActionPerformed(evt);
            }
        });

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        jLabel2.setText("Maien");

        chN3na3.setText("N3na3  .75");

        chMilk.setText("Milk 1.5");

        chToast.setText("Toast 1.25");
        chToast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chToastActionPerformed(evt);
            }
        });

        jLabel3.setText("Subtotal");

        jScrollPane1.setViewportView(txtsub);

        jScrollPane4.setViewportView(txttax);

        jScrollPane5.setViewportView(txttotal);

        jLabel4.setText("Tax");

        jLabel5.setText("Total");

        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        jLabel6.setText("Addation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnexit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnclear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnenter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radcola)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(radtea))
                            .addComponent(radyansun)
                            .addComponent(radcoffe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                        .addComponent(jScrollPane5)
                        .addComponent(jScrollPane4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chMilk)
                                .addComponent(chN3na3)
                                .addComponent(chToast)))))
                .addGap(1, 1, 1))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radtea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radcoffe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radyansun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radcola)
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnenter)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chN3na3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chMilk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chToast)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnclear)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(btnexit))))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radteaActionPerformed
        // select tea option:
        if (radtea.isSelected())
       radcola.setSelected(false);
        radcoffe.setSelected(false);
        radyansun.setSelected(false);
    }//GEN-LAST:event_radteaActionPerformed

    private void radcolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radcolaActionPerformed
        // select cola option:
        if (radcola.isSelected())
       radtea.setSelected(false);
        radcoffe.setSelected(false);
        radyansun.setSelected(false);
    }//GEN-LAST:event_radcolaActionPerformed

    private void chToastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chToastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chToastActionPerformed

    private void radcoffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radcoffeActionPerformed
        // select coffee option:
        if (radcoffe.isSelected())
       radcola.setSelected(false);
        radtea.setSelected(false);
        radyansun.setSelected(false);
    }//GEN-LAST:event_radcoffeActionPerformed

    private void radyansunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radyansunActionPerformed
        // select yansun option:
        if (radyansun.isSelected())
       radcola.setSelected(false);
        radcoffe.setSelected(false);
        radtea.setSelected(false);
    }//GEN-LAST:event_radyansunActionPerformed

    private void btnenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenterActionPerformed

      // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("0.00");
        double total ;
        double subtotal=0 ;
        final double TaxRate=.15 ;
        double tax ;
        if (radtea.isSelected()) {
          subtotal= subtotal + 1 ;     
        }else if (radyansun.isSelected()) {
            subtotal= subtotal + 1.25 ;
        }else if (radcoffe.isSelected()) {
            subtotal= subtotal + 1.5 ;
        }else if (radcola.isSelected()) {
            subtotal= subtotal + 2.5 ;
        }
        if (chN3na3.isSelected()) {
            subtotal= subtotal + .75 ;
        }if (chMilk.isSelected()) {
            subtotal= subtotal + 1.5 ;
        }if (chToast.isSelected()) {
            subtotal= subtotal + 1.25 ;
        }
        txtsub.setText(Double.toString(subtotal ));
    subtotal = Double.parseDouble(txtsub.getText());
    tax =subtotal * TaxRate ;
    total =tax +subtotal ;
    
    txttax.setText(Double.toString(tax ));
    txttotal.setText(Double.toString(total ));
    
    txtsub.setText(df.format(subtotal));
    txttax.setText(df.format(tax));
    txttotal.setText(df.format(total));
    }//GEN-LAST:event_btnenterActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // exit program:
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // clear all fields:
        radtea.setSelected(false);
        radcoffe.setSelected(false);
        radcola.setSelected(false);
        radyansun.setSelected(false);
        
        chN3na3.setSelected(false);
        chMilk.setSelected(false);
        chToast.setSelected(false);
        txtsub.setText("");
        txttotal.setText("");
        txttax.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(coffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(coffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(coffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(coffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new coffee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnenter;
    private javax.swing.JButton btnexit;
    private javax.swing.JCheckBox chMilk;
    private javax.swing.JCheckBox chN3na3;
    private javax.swing.JCheckBox chToast;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JRadioButton radcoffe;
    private javax.swing.JRadioButton radcola;
    private javax.swing.JRadioButton radtea;
    private javax.swing.JRadioButton radyansun;
    private javax.swing.JTextPane txtsub;
    private javax.swing.JTextPane txttax;
    private javax.swing.JTextPane txttotal;
    // End of variables declaration//GEN-END:variables
}
